### ISSUE TITLE
Cannot get theme modifications to render (color changes)

### ISSUE THREAD

**Issue by houstonhaynes** [64bitpandas/amethyst#2]
**Describe the bug**
I'm looking to get a templated version of the Amethyst theme to "change colors". I've *both* changed the colors.scss and custom.scss and haven't seen anything shift. I've tried the noted flags such as `hugo server --disableFastRender` in order to get "full rebuilds".

**Expected behavior**
Site color scheme changes with modification of either colors.scss or custom.scss

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Win11
 - Browser: Chrome

**Additional context**
Just for "laughs" I used the following colors just *to see **something** different*

```css
:root {
    --light: #faf8f8;
    --dark: #141021;
    --secondary: #d98d00; /* Orange tone for secondary */
    --tertiary: #ff9148; /* Orange tone for tertiary */
    --visited: #d97c00; /* Orange tone for visited */
    --primary: #ff825c; /* Main orange color for primary */
    --gray: #3f3f3f;
    --lightgray: #f0f0f0;
    --outlinegray: #dadada;
    --million-progress-bar-color: var(--secondary);
    --highlighted: #ffbf8e; /* Lighter orange tone for highlighted */
    --header: #fdaa7b; /* Orange tone for header */
    --title: rgb(232, 139, 79); /* Orange tone for title */
    --scrollbar: gray;
    --scrollbar-track: #DDD;
}

[saved-theme="dark"] {
    --light: #1e1e21 !important;
    --dark: #f7f2fa !important;
    --secondary: #e7a100 !important; /* Orange tone for secondary */
    --visited: #e19600 !important; /* Orange tone for visited */
    --tertiary: #b28a00 !important; /* Orange tone for tertiary */
    --primary: #f58382 !important; /* Retained the original primary color */
    --gray: #d4d4d4 !important;
    --lightgray: #292633 !important;
    --outlinegray: #343434 !important;
    --highlighted: #574010;
    --header: #38c8f8;
    --title: rgba(250, 153, 8, 0.881);
    --scrollbar: rgb(177, 177, 177);
    --scrollbar-track: rgb(51, 51, 51);
}

```

and here's the output of my console when I run the command

```powershell
PS C:\repos\fsharpnotes> make serve -B
hugo-obsidian -input=content -output=assets/indices -index -root=.
Scraping content
[Parsing note] /_index => found: 16 links
[Parsing note] /example/_index => found: 4 links
[Parsing note] /example/collapsed/3rd-level/4th-level => found: 1 links
[Parsing note] /example/collapsed/3rd-level/_index => found: 0 links
[Parsing note] /example/collapsed/_index => found: 0 links
[Parsing note] /example/hidden => found: 2 links
[Parsing note] /example/table-of-contents/_index => found: 3 links
[Parsing note] /example/table-of-contents/with-toc => found: 6 links
[Parsing note] /example/table-of-contents/without-toc => found: 1 links
[Parsing note] /features/_index => found: 0 links
[Parsing note] /features/buttons => found: 0 links
[Parsing note] /features/callouts => found: 1 links
[Parsing note] /features/columns => found: 0 links
[Parsing note] /features/details => found: 0 links
[Parsing note] /features/expand => found: 0 links
[Parsing note] /features/languages => found: 1 links
[Parsing note] /features/latex => found: 0 links
[Parsing note] /features/mermaid => found: 2 links
[Parsing note] /features/section/_index => found: 0 links
[Parsing note] /features/section/first-page => found: 0 links
[Parsing note] /features/section/second-page => found: 0 links
[Parsing note] /features/tabs => found: 0 links
[Parsing note] /setup/_index => found: 0 links
[Parsing note] /setup/config => found: 8 links
[Parsing note] /setup/custom Domain => found: 1 links
[Parsing note] /setup/editing => found: 7 links
[Parsing note] /setup/hosting => found: 6 links
[Parsing note] /setup/ignore notes => found: 1 links
[Parsing note] /setup/obsidian => found: 3 links
[Parsing note] /setup/preview changes => found: 3 links
[Parsing note] /setup/search => found: 1 links
[Parsing note] /setup/setup => found: 6 links
[Parsing note] /setup/troubleshooting => found: 11 links
[Parsing note] /setup/updating => found: 0 links
[DONE] in 20ms
Ignored 0 private files
Parsed 84 total links
Removed 50 external and non-markdown links
hugo server --enableGitInfo --minify --bind=0.0.0.0 --baseURL=http://localhost --port=1313 --appendPort=true
Watching for changes in C:\repos\fsharpnotes\{archetypes,assets,content,data,i18n,layouts,static}
Watching for config changes in C:\repos\fsharpnotes\config.yaml, C:\repos\fsharpnotes\go.mod
Start building sites …
hugo v0.116.1-3e1ea030a5897addaf9d113d0826709fe07f77c0 windows/amd64 BuildDate=2023-08-01T07:24:54Z VendorInfo=gohugoio

WARN  Expand shortcode is deprecated. Use 'details' instead.

                   | EN
-------------------+-----
  Pages            | 49
  Paginator pages  |  0
  Non-page files   |  4
  Static files     | 79
  Processed images |  0
  Aliases          |  5
  Sitemaps         |  1
  Cleaned          |  0

Built in 188 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 0.0.0.0)
Press Ctrl+C to stop
```
