### ISSUE TITLE
Having a deployment bug 

### ISSUE THREAD

**Issue by voidmain443** [64bitpandas/amethyst#8]
**Describe the bug**
I chage all step of the workflow and push the code but the deployment is show me the error about the Jekyll.?
I don't want to use Jekyll that is why I use Hugo. but the deployment code is not show the Jekyll but the rendering is show me the __layout__ of the error of Jekyll. 

Can you help me ?

**To Reproduce**
```
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: deploy  # deploying branch
          cname: voidmain443.github.io

```

**Expected behavior**
it have to be publish but it is doesn't. 

**Screenshots**
![image](https://github.com/64bitpandas/amethyst/assets/83549147/b96e20ed-d846-46ff-96b2-bbf22b37d213)

it is different here that the Jekyll  is not on the official docs . 

![image](https://github.com/64bitpandas/amethyst/assets/83549147/2d42d5e1-31f0-4b70-8b93-586a506c861b)

![image](https://github.com/64bitpandas/amethyst/assets/83549147/5f2f8d36-f671-44ad-856c-12c9b8ccc944)

**Desktop (please complete the following information):**
 - Device: GitHub workflow
 - OS: Mac GitHub workflow 

**Additional context**
